### ISSUE TITLE
Replace {{projectId}} with actual project.

### ISSUE THREAD

**Issue by sduskis** [googleapis/nodejs-bigtable#196]
The nodejs-bigtable client uses {{projectId}} as a placeholder.  Ideally, we use `process.env.GOOGLE_CLOUD_PROJECT` or `process.env.GCLOUD_PROJECT` for our system tests, and otherwise force users to set projectId.

**Comment by JustinBeckwith** [comment]
I'd like to understand more as well.  When you say it uses `{{projectId}}` - is that leaked to the customer?  Or is this an implementation detail?

**Comment by stephenplusplus** [comment]
No, just an implementation detail. If the user doesn't explicitly provide a `projectId` parameter in the configuration object passed to the constructor (`new Storage({projectId: '...'})`), we default it to `{{projectId}}`. We do this, because some API calls require a user's project ID as part of the request object. For example, if it's supposed to be part of the path of a Compute resource, or something. Before we send *any* API request, we dig through that whole request object for `{{projectId}}`, and replace it with a real value that the auth library returns to us. If we can't, we return an error at that time.

**Comment by JustinBeckwith** [comment]
If that's working today, I'm not sure why we'd change it 🤷‍♂️  @sduskis is this causing trouble?

**Comment by sduskis** [comment]
I like the feature.  I guess my main objective is that the he project id ought to be immutable.  The problem with node, the projectId is resolved after the first RPC.  This causes some subtle problems relating to assumptions built into the client's constructors that need to be fixed.

```this.name = `${parent.name}/child-type/{this.id}`;```

This assumption breaks in for the child classes.  `parent.name` ultimately gets `bigtable.projectId`, which is likely to be `'{{projectId}}'`.  This would happen in cases where a user just creates objects as the first part of their application, and then call RPC driving methods later.  Here's some evidence of the problem:

- (AppProfile system test)[https://github.com/googleapis/nodejs-bigtable/blob/4b899497a06309a1dd5955f95f75d355d659bbaa/system-test/bigtable.js#L203]
- (Table system test)[https://github.com/googleapis/nodejs-bigtable/blob/4b899497a06309a1dd5955f95f75d355d659bbaa/system-test/bigtable.js#L349]
- (Table admin sample)[https://github.com/googleapis/nodejs-bigtable/blob/6700b0f28cb752b2c42ab12a88bb95307e823478/samples/tableadmin.js#L232]

Is there a way to resolve the actual `projectId` in the index.js constructor to maintain "immutability"?

I did my best to find out how this issue is handled in (nodejs-spanner)[https://github.com/googleapis/nodejs-bigtable], which is where I came up with the original request, although it could be that I'm missing something important with their implementation.

**Comment by JustinBeckwith** [comment]
Hmmm.  The logic to get the project Id does need to remain async, due to the metadata server for adc and reading from the filesystem for cases where the user gives us a service account json.  

And you can't have async code inside of the constructor (at least I don't think).

Can we defer the instantiation of the service objects until the async operation to load credentials is complete?

**Comment by sduskis** [comment]
How about this: The `Bigtable` service object requires a `projectId`, and we provide an async method to construct a `Bigtable` object without the projectId.

**Comment by stephenplusplus** [comment]
> And you can't have async code inside of the constructor (at least I don't think).

Yep, that's right.

> [AppProfile system test](https://github.com/googleapis/nodejs-bigtable/blob/4b899497a06309a1dd5955f95f75d355d659bbaa/system-test/bigtable.js#L203)
> [Table system test](https://github.com/googleapis/nodejs-bigtable/blob/4b899497a06309a1dd5955f95f75d355d659bbaa/system-test/bigtable.js#L349)

Those could be made prettier if we provide the project ID to the Bigtable constructor [here](https://github.com/googleapis/nodejs-bigtable/blob/4b899497a06309a1dd5955f95f75d355d659bbaa/system-test/bigtable.js#L33).

> [Table admin sample](https://github.com/googleapis/nodejs-bigtable/blob/6700b0f28cb752b2c42ab12a88bb95307e823478/samples/tableadmin.js#L228)

I believe we have tried to keep the `name` and `id` properties out of documentation. In this case, it's a piece of information the user needs, since the name isn't repeated anywhere in the `table.metadata` object (which we don't try to hide). Since you've been working on making `id` the shorthand name, as opposed to a full resource path like the docs show, that would change the sample to only print out "cf4". That would clean up the sample docs, leaving `name` as a private property that really only matters to us.

If the user provides a `projectId` to the constructor, they won't see the placeholder when they log the "private" properties. If they don't provide one, but we can detect one for them, even if they encounter a placeholder, I would think the convenience tradeoff is worth it to them. And if it's not, they can just provide a `projectId` to the constructor, and not have to deal with it.

**Comment by sduskis** [comment]
@theacodes: FYI

**Comment by sduskis** [comment]
+1 on `name` being private.  Still, there's plenty of issues trying to manage {{projectId}} properly.  We either build a more elaborate method of propagating the resolution of the projectId, or we force users to set projectId at startup.

I strongly prefer that we force users to set projectId at start up time, which would reduce complexity.

**Comment by stephenplusplus** [comment]
What issues? We do this across all APIs. If there are issues, we should figure them out or change everywhere.

**Comment by sduskis** [comment]
I poked around a bit more, and perhaps the only issue is some impact on runtime performance.

**Comment by sduskis** [comment]
If users set a projectId, we shouldn't call the replaceToken method.  That would improve performance a bit.
