### ISSUE TITLE
TypeError: Class constructor Bigtable cannot be invoked without 'new'

### ISSUE THREAD

**Issue by moander** [googleapis/nodejs-bigtable#215]
`nodejs-bigtable` does not behave like the other `@google-cloud` libraries

#### Environment details

  - `@google-cloud/bigtable` version: master branch (no error on 0.14.0)

#### Steps to reproduce

```js
const Bigtable = require('@google-cloud/bigtable');

new require('@google-cloud/datastore')();
new require('@google-cloud/storage')();
new require('@google-cloud/pubsub')();
new require('@google-cloud/bigquery')();
new require('@google-cloud/dns')();
new Bigtable(); // Success
new require('@google-cloud/bigtable')(); // Error
```

**Comment by kolodny** [comment]
This is by design, you now need to create a Bigtable instance with the `new` keyword

See the discussion at https://github.com/googleapis/nodejs-bigtable/pull/158#discussion_r194210945

The other libraries were grandfathered into the optional new variant and have to do some [Proxy trickery](https://github.com/googleapis/nodejs-storage/issues/173#issuecomment-396789595) to make it work with ES classes, however since this library is still alpha, we chose to be more "correct" in how class objects are created.

Feel free to reopen the issue if that doesn't resolve your concerns.

**Comment by moander** [comment]
I am using the `new` keyword:

```js
new require('@google-cloud/bigtable')()
```

**Comment by kolodny** [comment]
Ahh, got it, that just seems to be a js parsing oddity. The following works as expected:

```js
const Bigtable = require('@google-cloud/bigtable');
const bigtable = new Bigtable(/*...*/);

```

**Comment by moander** [comment]
Yes and that makes it stand out from all other `@google-cloud` i have in my project. It is the lack of continuity I wanted to report :)

**Comment by kolodny** [comment]
Ahh, understood, reopened.

**Comment by kolodny** [comment]
@JustinBeckwith Any thoughts on this?

**Comment by JustinBeckwith** [comment]
I'm a little torn.  Adding the proxy trick does make this nice and easy.  @ofrobots since we need to have this for GA libraries anyway, what do you think of just supporting it everywhere?

**Comment by ofrobots** [comment]
Consistency is good, at some level you have to become inconsistent. We cannot use the proxy trick for all classes as there is performance impact. I would be okay with doing _only_ at the top-level export of a module.

**Comment by JustinBeckwith** [comment]
@kolodny doing this for the top level export would fix the issue, right?

**Comment by kolodny** [comment]
Correct I'll send out a PR for this soon

I would wait off on https://github.com/googleapis/nodejs-bigtable/issues/224 until this is done
