### ISSUE TITLE
examples include HTML which jsdoc does not render

### ISSUE THREAD

**Issue by bcoe** [googleapis/nodejs-bigtable#574]
I noticed while QAing some of our other doc fixes, that there are a few places where we optimistically include HTML in our example content, even though this isn't supported by our current JSDoc template:

https://googleapis.dev/nodejs/bigtable/latest/Bigtable.html#Bigtable-examples

It would be good to fix this up:

CC: @frankyn, @billyjacobson

**Comment by frankyn** [comment]
Billy hit this during review, and I did as well for Storage. Thanks for filing an issue for it.
It might be an issue across libraries.

**Comment by callmehiphop** [comment]
@bcoe this is leftover from our original docs solution. The `//-` token was actually meant to indicate we've come to a new sample. I've been updating these to use `@example` and `<caption>` when I come across them, but we might want to open an issue to make that fix across the board.

**Comment by bcoe** [comment]
@callmehiphop @frankyn should we extend the plugin to support this additional syntax, or do we think moving away from using the custom approach is better?

**Comment by callmehiphop** [comment]
@bcoe I think creating a JSDoc plugin *might* be better, just because it would require less effort and fix this issue across all our veneers libraries. 

I like `@example <caption>` but as it is we have to write the entire caption on a single line, which is not great for examples that require a lengthy writeup. 

/cc @stephenplusplus because I bet you have some thoughts here!

**Comment by frankyn** [comment]
I have questions:
1. Would it make sense to split off additional samples into their own file instead of directly adding them into jsdoc documentation?
2. IIUC,  `@example/<caption>` is the canonical expectation for jsdoc when multiple examples are present. Right now they aren't being displayed correctly, but that's not due to the plugin. Is this something that can be fixed without adding customer syntax, e.g. `//-`? If so, then we should do that instead of relying on custom syntax + plugin.

**Comment by stephenplusplus** [comment]
> Would it make sense to split off additional samples into their own file instead of directly adding them into jsdoc documentation?

I think this is a pro/con story, where pro: organized, testable, and con: separate from code (more hurdles for simple contributions), more work than necessary (? some of these are just a quick "here's how you pass *this* option")

> IIUC,  `@example/<caption>` is the canonical expectation for jsdoc when multiple examples are present. Right now they aren't being displayed correctly, but that's not due to the plugin. Is this something that can be fixed without adding customer syntax, e.g. `//-`? If so, then we should do that instead of relying on custom syntax + plugin.

The `@example/<caption>` syntax is not ideal because: 
```
 * @example <caption><h6>Simulating a File System</h6><p>With `autoPaginate: false`, it's possible to iterate over files which incorporate a common structure using a delimiter.</p><p>Consider the following remote objects:</p><ol><li>"a"</li><li>"a/b/c/d"</li><li>"b/d/e"</li></ol><p>Using a delimiter of `/` will return a single file, "a".</p><p>`apiResponse.prefixes` will return the "sub-directories" that were found:</p><ol><li>"a/"</li><li>"b/"</li></ol></caption>
```

([source](https://github.com/googleapis/nodejs-storage/blob/b1c05b27029215c8bc313a8f4f16ff13d5af2391/src/bucket.ts#L2101:
))

So, as long as that's actually the best option that JSDocs is giving us, I think the `//-` thing is better. I would vote that we write a plug-in to parse those content blocks out and run it through a Markdown -> HTML converter.

**Comment by bcoe** [comment]
@stephenplusplus @callmehiphop @frankyn, I found a bunch of examples of this behavior in `@google-cloud/storage`, and the problem was just that `jsdoc` required that the example was one line after `</caption>` in the docstring.

**Comment by JustinBeckwith** [comment]
In #689 I fixed a lot of the mechanical problems we were running into, and it's a lot better now. However - there are still URLs inside of the `@example` bodies in several places, that don't get rendered properly.  I honestly don't know how/if this can be fixed to be honest.  For example:

![image](https://user-images.githubusercontent.com/534619/78416230-61a9e300-75dc-11ea-8f05-431c18986e0b.png)

I'm just not sure if there's any feature of jsdoc that will let us interweave example code with plain HTML/text.  

Thoughts @bcoe @hegemonic ?
