### ISSUE TITLE
Unexpected poor performance when querying zero keys

### ISSUE THREAD

**Issue by ansf** [googleapis/nodejs-bigtable#888]
When querying for zero keys, the query becomes very slow and leads to high CPU usage on the BigTable nodes.

From my understanding this is unexpected.

In the go repo, I found some hints that this kind of query leads to a full table scan:
https://github.com/googleapis/google-cloud-go/blob/f94389e79f58eb29eaa48ed69017fc82334c3acd/bigtable/bigtable.go#L183

Maybe we can check for empty keys in the client library, or improve the documentation for this case?

#### Environment details

  - Node.js version: 16.3.0
  - yarn version: 1.22.10
  - `@google-cloud/bigtable` version: 3.5.0

#### Steps to reproduce

Do the following query on a large table:

```
await table.getRows({ keys: [] })
```

**Comment by kaioduarte** [comment]
There's a warning on the "Using filters" page about that; not sure when it was added, though.

https://cloud.google.com/bigtable/docs/using-filters#row-selection

**Comment by danieljbruce** [comment]
Likely fixed.

**Comment by meredithslota** [comment]
This is fixed in the documentation — querying with empty keys prompts a full table scan. The specific warning now says: "Warning: If you don't specify a row key or range of rows for a filter, the filter is applied to all rows in a full table scan. One exception to this is [row key regex](https://cloud.google.com/bigtable/docs/using-filters#row-key-regex), which can restrict the row range in certain cases if the regex is a fixed prefix."
