### ISSUE TITLE
Bubble up 'metadata' event for mutate request

### ISSUE THREAD

**Issue by mutianf** [googleapis/nodejs-bigtable#991]
mutate request should emit 'metadata' event in the manual layer so applications can get useful metrics from response headers like gfe 'server-timing'

**Comment by danieljbruce** [comment]
I looked at what I get back from an error on the following test when using mutate instead of insert:

https://github.com/googleapis/nodejs-bigtable/blob/main/test/errors.ts#L105

It appears that the error includes metadata:

err.metadata = `{"grpc-server-stats-bin":[{"type":"Buffer","data":[0,0,116,73,159,3,0,0,0,0]}]}`

Do you mean `metadata` should be available when data is sent back as well?

**Comment by danieljbruce** [comment]
Clarification: the bug is not talking about the metadata in the error. It is talking about the metadata grpc response which indeed includes headers like `'server-timing'`.

**Comment by danieljbruce** [comment]
https://github.com/googleapis/nodejs-bigtable/pull/1178 is a possible fix.

**Comment by danieljbruce** [comment]
https://github.com/googleapis/nodejs-bigtable/pull/1180 contains the changes that include making metadata available to the user, but it seems like we are satisfied with providing it on the returned stream.

**Comment by danieljbruce** [comment]
https://github.com/googleapis/nodejs-bigtable/pull/1178 merged. Let me know if any more changes are needed.
